name: Publish NStack.Core to nuget
on:
  push:
    tags:
      - v*

jobs:

  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.*

      - name: minver-cli
        run: |
          dotnet tool install --global minver-cli --version 2.4.0
          echo "MINVERVERSIONOVERRIDE=$(minver -t v -d rc)" >> $GITHUB_ENV

      #- name: Install dependencies
      #   run: dotnet restore

      #- name: Build
      #  run: dotnet build --configuration Release --no-restore

      #- name: Pack nuget package with symbols
      #  run: dotnet pack --include-symbols
      
      - name: Publish NStack.Core
        id: publish_nuget
